CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);

CREATE TABLE groups(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_groups_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE tasks(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    note TEXT,
    solution_difficulty INTEGER NOT NULL DEFAULT 0,
    time_difficulty INTEGER NOT NULL,
    highlighted BOOLEAN NOT NULL DEFAULT FALSE,
    deadline DATE,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    group_id BIGINT NOT NULL,

    CONSTRAINT fk_tasks_group FOREIGN KEY (group_id) REFERENCES groups(id),

    CONSTRAINT chk_solution_difficulty CHECK (solution_difficulty BETWEEN 0 AND 3),
    CONSTRAINT chk_time_difficulty CHECK (time_difficulty BETWEEN 1 AND 3),
    CONSTRAINT chk_status CHECK (status BETWEEN 1 AND 3)
);